### Login
POST http://localhost:3002/api/login HTTP/1.1
Content-Type: application/json
{
    "email":"m@m.fr",
    "password":"azerty"
}


### Récupération des utilisateurs

GET http://localhost:3002/api/users
Content-Type: application/json


### Récupération d'un utilisateur

GET http://localhost:3002/api/user/5
Content-Type: application/json

### Création d'un utilisateur

POST http://localhost:3002/api/register HTTP/1.1
Content-Type: application/json

{ 
    "firstname" : "Chuck",
     "lastname" : "Norris",
     "email"    : "chuck.norrirs@test.tu",
     "password" : "azerty",
     "phone"    : "06-52-14-52-32"
 }


### Test identification

POST http://localhost:3002/api/login HTTP/1.1
Content-Type: application/json

{ "email" : "allo@test2.fr", "password" : "toto" }
