### Création d'un utilisateur

POST http://localhost:3001/api/register HTTP/1.1
Content-Type: application/json

{ 
    "firstname" : "Chuck",
     "lastname" : "Norris",
     "email"    : "chuck.norris@test.fr",
     "password" : "azerty",
     "phone"    : "0652145232"
 }

### Login Test identification Admin
POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{ "email" : "m@m.fr", "password" : "azerty" }


### Login Test identification membre
POST http://localhost:3002/api/login HTTP/1.1
Content-Type: application/json

{ "email" : "a@a.fr", "password" : "azerty" }

### Récupération des utilisateurs

GET http://localhost:3002/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AbS5mciIsImlhdCI6MTY3ODExMTI3NiwiZXhwIjoxNjc4MTk3Njc2fQ.1i0JyBNoXNQFrZviN8rYURr6ccCZFpWFYq8MPksEjfs

### Récupération d'un utilisateur par son propriétaire

GET http://localhost:3002/api/user/19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5mciIsImlhdCI6MTY3ODExMzg3NCwiZXhwIjoxNjc4MjAwMjc0fQ.KqvHXasnWv-WXPq1bWZ58NEoU3LwGabz_RTtqUOB7-c


### Récupération d'un utilisateur par un admin

GET http://localhost:3002/api/admin/user/19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AbS5mciIsImlhdCI6MTY3ODExMzk2NiwiZXhwIjoxNjc4MjAwMzY2fQ.l_ePcPWpFcUQx5o9M0qokGifJEk0RRG2HJWBjXDG50Y


### Récupération de la liste des animaux

GET http://localhost:3002/api/animals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AbS5mciIsImlhdCI6MTY3ODExMzk2NiwiZXhwIjoxNjc4MjAwMzY2fQ.l_ePcPWpFcUQx5o9M0qokGifJEk0RRG2HJWBjXDG50Y