### Récupération des users

GET http://localhost:3000/api/users
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNuIiwiaWF0IjoxNjc2NjI4NzA0fQ.UiDbEddsvf_qeY_GdvDvgbl1sc9llcsFeQwMBLjoE3o

###

POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{ "email" : "kev@kev.com", "password" : "kevin" }