services:
  - type: web
    name: adopte-un-humain-api
    runtime: node
    plan: free
    region: frankfurt
    repo: https://github.com/miazarre/Adopte-un-Humain-Back.git
    buildCommand: npm install
    startCommand: npm run render_start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: PGHOST
        fromDatabase:
          name: ah-database
          property: host
      - key: PGPORT
        fromDatabase:
          name: ah-database
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: ah-database
          property: database
      - key: PGUSER
        fromDatabase:
          name: ah-database
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: ah-database
          property: password
      - key: INITIAL_ADMIN_EMAIL
        sync: false
      - key: INITIAL_ADMIN_PASSWORD
        sync: false
    autoDeploy: false
  - type: web
    name: adopte-un-humain
    runtime: static
    repo: https://github.com/miazarre/Adopte-un-Humain-Front.git
    buildCommand: yarn build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BASE_URL
        sync: false

databases:
  - name: ah-database
    plan: free
    region: frankfurt
